### ISSUE TITLE
Feature request: gutterWidth prop

### ISSUE THREAD

**Issue by volkandkaya** [zoover/react-grid-system#8]
Would be great to have a gutterWidth prop that takes a number or array (left, right).

**Comment by gerbenmeyer** [comment]
You can already set the gutterWidth (one number only though) through context types, have you tried that?

**Comment by volkandkaya** [comment]
Just tried putting 0 in and it isn't working. My guess is gutterWidth || defaultGutterWidth. I hacked it together with "0".

**Comment by gerbenmeyer** [comment]
Good point about the falsy 0, that is definitely something which should be fixed.

**Comment by volkandkaya** [comment]
@gerbenmeyer would love this to be implement soon, I keep getting warning errors.

**Comment by gerbenmeyer** [comment]
This should be fixed now in the latest version (2.0.4).
