### ISSUE TITLE
Feature request: change from [1, ..., 12] grid to number

### ISSUE THREAD

**Issue by volkandkaya** [zoover/react-grid-system#9]
With that change made I can use 0.5 etc for different grid sizes. Doing that means it should also not break anything.

**Comment by volkandkaya** [comment]
@gerbenmeyer any chance of this in 2.1?

**Comment by gerbenmeyer** [comment]
Sure, seems like a good idea, just thinking about whether there would be any downside to it.

**Comment by gerbenmeyer** [comment]
So it's there, version 2.1.
